---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-blackbox-exporter-config-map
  namespace: loki-stack
  labels:
    app: prometheus-blackbox-exporter
data:
  blackbox.yaml: |
    modules:
      http_2xx:
        http:
          preferred_ip_protocol: ip4
        prober: http
        timeout: 60s

      icmp:
        prober: icmp
        timeout: 10s
        icmp:
          preferred_ip_protocol: ip4